## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugostory"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[params.social]
  email = "kontakt@fijab.se"
  facebook = "https://www.facebook.com/profile.php?id=100092133390750"

enableRobotsTXT = true
